import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils"
export const metadata = {
  title: "Shadcn Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={cn(
        "bg-background font-sans antialiased"
      )}>{children}</body>
    </html>
  );
}
